export interface DiagnosticKeySpec<K extends string> {
  key: K;
  zh: string;
  en: string;
  example: string;
  params?: Record<string, string | number>;
}

export const PARSER_DIAGNOSTIC_SPECS = [
  {
    key: "expected_directive",
    zh: "当解析器期望读到指令行时，却遇到了普通文本。",
    en: "A directive was expected, but a plain source line was found instead.",
    example: "示例 / Example: hello world",
    params: { lineText: "hello world" },
  },
  {
    key: "meta_name_not_allowed",
    zh: "`@meta` 不能携带块名称。",
    en: "`@meta` does not accept a block name.",
    example: "示例 / Example: @meta report",
  },
  {
    key: "block_name_required",
    zh: "需要名称的指令缺少块名称。",
    en: "A named directive is missing its required block name.",
    example: "示例 / Example: @table",
    params: { directive: "table" },
  },
  {
    key: "unsupported_directive",
    zh: "使用了当前 DSL 尚未支持的指令。",
    en: "The source used a directive that is not supported by the DSL.",
    example: "示例 / Example: @window sales",
    params: { directive: "window" },
  },
  {
    key: "invalid_meta_entry",
    zh: "`@meta` 块中的条目不符合 `key: value` 语法。",
    en: "A line in `@meta` did not follow `key: value` syntax.",
    example: "示例 / Example: title = report",
    params: { lineText: "title = report" },
  },
  {
    key: "invalid_meta_key",
    zh: "`@meta` 中的键不是合法标识符。",
    en: "A `@meta` key was not a valid identifier.",
    example: "示例 / Example: report-title: demo",
    params: { key: "report-title" },
  },
  {
    key: "invalid_entry",
    zh: "通用键值行无法解析。",
    en: "A generic key-value line was malformed.",
    example: "示例 / Example: path = ./plugin.ts",
    params: { lineText: "path = ./plugin.ts" },
  },
  {
    key: "empty_table",
    zh: "`@table` 块没有任何表头或数据内容。",
    en: "A `@table` block was empty.",
    example: "示例 / Example: @table sales",
    params: { table: "sales" },
  },
  {
    key: "table_row_width_mismatch",
    zh: "CSV 数据行列数与表头列数不一致。",
    en: "A CSV row width did not match the header width.",
    example: "示例 / Example: header has 3 columns, row has 2",
    params: { table: "sales", expected: 3, actual: 2 },
  },
  {
    key: "compute_target_required",
    zh: "`@compute` 块缺少必需的 `target:` 声明。",
    en: "A `@compute` block omitted its required `target:` declaration.",
    example: "示例 / Example: @compute sales",
    params: { table: "sales" },
  },
  {
    key: "plot_deps_required",
    zh: "`@plot` 块缺少必需的 `deps:` 声明。",
    en: "A `@plot` block omitted its required `deps:` declaration.",
    example: "示例 / Example: @plot sales",
    params: { table: "sales" },
  },
  {
    key: "invalid_identifier",
    zh: "标识符不符合 `.sheet` 的命名规则。",
    en: "An identifier did not match the allowed `.sheet` syntax.",
    example: "示例 / Example: total-price[number]",
    params: { identifier: "total-price", context: "target" },
  },
  {
    key: "duplicate_identifier",
    zh: "同一上下文中声明了重复标识符。",
    en: "Two identifiers that must be unique were repeated in the same context.",
    example: "示例 / Example: target: total[number], total[number]",
    params: { identifier: "total", context: "target" },
  },
  {
    key: "invalid_column_declaration",
    zh: "表头列声明不符合 `name[type]` 语法。",
    en: "A table header cell did not match `name[type]` syntax.",
    example: "示例 / Example: price(number)",
    params: { declaration: "price(number)", table: "sales" },
  },
  {
    key: "list_must_contain_name",
    zh: "要求至少一个名称的列表为空。",
    en: "A comma-separated list that requires at least one name was empty.",
    example: "示例 / Example: deps:",
    params: { context: "deps" },
  },
  {
    key: "invalid_function_parameter",
    zh: "`@func` 参数声明格式错误。",
    en: "A `@func` parameter declaration was malformed.",
    example: "示例 / Example: @func tax(price(number)) -> number",
    params: { param: "price(number)", context: "@func tax" },
  },
  {
    key: "plugin_path_required",
    zh: "`@plugin` 块缺少必需的 `path:`。",
    en: "A `@plugin` block omitted its required `path:` entry.",
    example: "示例 / Example: @plugin finance",
    params: { alias: "finance" },
  },
  {
    key: "unknown_plot_table",
    zh: "解析 `@plot` 时引用了尚未声明的表。",
    en: "A `@plot` block referenced a table that had not been declared.",
    example: "示例 / Example: @plot missing",
    params: { table: "missing" },
  },
  {
    key: "empty_plot",
    zh: "`@plot` 块去掉空行和注释后没有有效内容。",
    en: "A `@plot` block had no usable content after filtering comments and blanks.",
    example: "示例 / Example: @plot sales",
    params: { table: "sales" },
  },
  {
    key: "plot_axes_required",
    zh: "bar 图缺少 `x` 或 `y` 轴定义。",
    en: "A bar plot omitted one or both required axes.",
    example: "示例 / Example: x: price without y",
    params: { table: "sales" },
  },
  {
    key: "invalid_plot_shorthand",
    zh: "plot 简写语法不符合支持的 bar 语法。",
    en: "A shorthand plot line did not match the supported bar shorthand shape.",
    example: "示例 / Example: bar price",
    params: { value: "bar price" },
  },
  {
    key: "unsupported_plot_type",
    zh: "请求了当前 demo 不支持的图表类型。",
    en: "A shorthand plot requested a plot type other than bar.",
    example: "示例 / Example: line price qty",
    params: { value: "line price qty" },
  },
  {
    key: "unsupported_plot_key",
    zh: "plot 块中出现了未支持的键。",
    en: "A keyed plot body used a field that is not supported.",
    example: "示例 / Example: legend: item",
    params: { key: "legend" },
  },
  {
    key: "invalid_func_signature",
    zh: "`@func` 指令行签名无法解析。",
    en: "A `@func` directive line did not match the supported signature syntax.",
    example: "示例 / Example: @func tax price[number] -> number",
    params: { signature: "@func tax price[number] -> number" },
  },
  {
    key: "func_body_expression_count",
    zh: "`@func` 块必须且只能包含一个表达式体。",
    en: "A `@func` block did not contain exactly one expression body.",
    example: "示例 / Example: function body has 0 or 2 expressions",
    params: { name: "tax" },
  },
  {
    key: "invalid_compute_statement",
    zh: "`@compute` 语句不符合 `target = expression` 语法。",
    en: "A `@compute` line did not match `target = expression`.",
    example: "示例 / Example: total: price * qty",
    params: { lineText: "total: price * qty" },
  },
  {
    key: "invalid_compute_target",
    zh: "计算列目标名不是合法标识符。",
    en: "A computed target name was not a valid identifier.",
    example: "示例 / Example: total-price = price * qty",
    params: { target: "total-price" },
  },
  {
    key: "unterminated_csv_quote",
    zh: "CSV 行中引号未闭合。",
    en: "A CSV line ended while still inside a quoted cell.",
    example: "示例 / Example: \"North,apple",
    params: { lineText: "\"North,apple" },
  },
  {
    key: "dynamic_parse_failed",
    zh: "`dynamic` 单元格无法按允许的顺序解析。",
    en: "A `dynamic` cell could not be parsed as null, number, boolean, or string.",
    example: "示例 / Example: custom non-scalar loader result",
    params: { rawValue: "[object Object]" },
  },
  {
    key: "declared_type_mismatch",
    zh: "单元格值与显式声明类型不匹配。",
    en: "A cell failed to parse as its explicitly declared type.",
    example: "示例 / Example: 商品[number] with value 苹果",
    params: { rawValue: "苹果", declaredType: "number" },
  },
  {
    key: "invalid_numeric_literal",
    zh: "表达式中的数字字面量格式错误。",
    en: "A numeric literal token in an expression was malformed.",
    example: "示例 / Example: 1.2.3",
    params: { value: "1.2.3" },
  },
  {
    key: "unexpected_expression_character",
    zh: "表达式中出现了无法识别的字符。",
    en: "An expression contained an unexpected raw character.",
    example: "示例 / Example: price $ qty",
    params: { character: "$" },
  },
  {
    key: "unexpected_expression_token",
    zh: "表达式解析分支遇到了意外 token。",
    en: "An expression parser branch saw an unexpected token.",
    example: "示例 / Example: price + )",
    params: { token: ")" },
  },
  {
    key: "expected_expression_token",
    zh: "表达式解析器期望某个 token，但实际遇到另一个。",
    en: "An expression parser expectation failed for the current token.",
    example: "示例 / Example: expected ) but found <eof>",
    params: { expected: ")", actual: "<eof>" },
  },
] as const satisfies readonly DiagnosticKeySpec<string>[];

export type ParserDiagnosticKey = (typeof PARSER_DIAGNOSTIC_SPECS)[number]["key"];

export const ANALYSIS_DIAGNOSTIC_SPECS = [
  {
    key: "duplicate_table_name",
    zh: "两个 `@table` 使用了相同表名。",
    en: "Two `@table` blocks used the same table name.",
    example: "示例 / Example: @table sales ... @table sales",
    params: { name: "sales" },
  },
  {
    key: "duplicate_function_name",
    zh: "两个 `@func` 使用了相同函数名。",
    en: "Two `@func` blocks used the same function name.",
    example: "示例 / Example: @func tax ... @func tax ...",
    params: { name: "tax" },
  },
  {
    key: "builtin_function_name_reserved",
    zh: "用户函数名与内建函数名冲突。",
    en: "A user-defined function name conflicts with a reserved builtin function name.",
    example: "示例 / Example: @func if(value[number]) -> number",
    params: { name: "if" },
  },
  {
    key: "duplicate_plugin_alias",
    zh: "两个 `@plugin` 使用了相同别名。",
    en: "Two `@plugin` blocks used the same alias.",
    example: "示例 / Example: @plugin finance ... @plugin finance",
    params: { name: "finance" },
  },
  {
    key: "unknown_compute_table",
    zh: "`@compute` 引用了不存在的表。",
    en: "A `@compute` block referenced a table that does not exist.",
    example: "示例 / Example: @compute missing",
    params: { table: "missing" },
  },
  {
    key: "unknown_function",
    zh: "引用了不存在的本地函数。",
    en: "A referenced local `@func` could not be found.",
    example: "示例 / Example: total = missing(price)",
    params: { name: "missing" },
  },
  {
    key: "recursive_function_call",
    zh: "`@func` 之间形成了递归调用环。",
    en: "One or more `@func` blocks formed a recursive call cycle.",
    example: "示例 / Example: a() -> b(); b() -> a()",
    params: { path: "a -> b -> a" },
  },
  {
    key: "unknown_plot_dependency",
    zh: "`deps:` 中声明了不存在的列依赖。",
    en: "A plot dependency name was not found in the table or computed outputs.",
    example: "示例 / Example: deps: price, missing",
    params: { dependency: "missing", table: "sales" },
  },
  {
    key: "unknown_plot_table",
    zh: "`@plot` 分析时引用了不存在的表。",
    en: "A plot referenced a table that does not exist at analysis time.",
    example: "示例 / Example: @plot missing",
    params: { table: "missing" },
  },
  {
    key: "unknown_reference",
    zh: "`@compute` 表达式引用了不存在的列或局部变量。",
    en: "A compute expression referenced a missing table/output/local symbol.",
    example: "示例 / Example: total = missing * qty",
    params: { name: "missing", table: "sales" },
  },
  {
    key: "function_arity_mismatch",
    zh: "函数调用的参数个数不匹配。",
    en: "A function call used the wrong number of arguments.",
    example: "示例 / Example: tax(price) when tax expects 2 args",
    params: { name: "tax", expected: 2, actual: 1 },
  },
  {
    key: "unsupported_function_call",
    zh: "函数调用形式不受支持。",
    en: "A function-like call did not match any supported builtin, local func, or plugin form.",
    example: "示例 / Example: a.b.c()",
    params: { callee: "a.b.c" },
  },
  {
    key: "unknown_plugin_alias",
    zh: "调用了未声明的 plugin 别名。",
    en: "A plugin alias used in analysis was not declared.",
    example: "示例 / Example: finance.tax(price)",
    params: { alias: "finance" },
  },
  {
    key: "unknown_plugin_export",
    zh: "调用了 plugin 中不存在的导出函数。",
    en: "A plugin export name used in analysis was not exposed by the plugin.",
    example: "示例 / Example: finance.missing(price)",
    params: { callee: "finance.missing" },
  },
  {
    key: "unknown_function_parameter_reference",
    zh: "`@func` 体中引用了未声明参数。",
    en: "A `@func` expression referenced a name that is not one of its parameters.",
    example: "示例 / Example: @func tax(price[number]) -> number / total * 2",
    params: { name: "total", func: "tax" },
  },
  {
    key: "type_mismatch",
    zh: "表达式推导类型与显式期望类型不一致。",
    en: "An expression type did not match the expected declared type.",
    example: "示例 / Example: target: label[string] / label = price * qty",
    params: { context: "@compute sales target label", expected: "string", actual: "number" },
  },
  {
    key: "plot_field_missing",
    zh: "plot 缺少必须字段，例如 `x` 或 `y`。",
    en: "A required plot field such as `x` or `y` was missing.",
    example: "示例 / Example: @plot sales / y: total",
    params: { table: "sales", field: "x" },
  },
  {
    key: "plot_field_not_in_deps",
    zh: "plot 字段引用的列未在 `deps:` 中声明。",
    en: "A plot field referenced a name that was not listed in `deps:`.",
    example: "示例 / Example: deps: price / y: total",
    params: { field: "y", value: "total" },
  },
  {
    key: "builtin_if_arity",
    zh: "`if` 调用参数个数不正确。",
    en: "The builtin `if` function was called with the wrong number of arguments.",
    example: "示例 / Example: if(cond, value)",
  },
  {
    key: "builtin_coalesce_arity",
    zh: "`coalesce` 至少需要一个参数。",
    en: "The builtin `coalesce` function was called with zero arguments.",
    example: "示例 / Example: coalesce()",
  },
  {
    key: "builtin_and_arity",
    zh: "`and` 至少需要一个参数。",
    en: "The builtin `and` function was called with zero arguments.",
    example: "示例 / Example: and()",
  },
  {
    key: "builtin_or_arity",
    zh: "`or` 至少需要一个参数。",
    en: "The builtin `or` function was called with zero arguments.",
    example: "示例 / Example: or()",
  },
  {
    key: "boolean_compatible_required",
    zh: "布尔位置接收到了非布尔兼容类型。",
    en: "A boolean-only position received a non-boolean-compatible type during analysis.",
    example: "示例 / Example: if(price * 0.9, a, b)",
    params: { context: "Argument 1 of if", actual: "number" },
  },
  {
    key: "number_compatible_required",
    zh: "数值位置接收到了非数值兼容类型。",
    en: "A numeric-only position received a non-number-compatible type during analysis.",
    example: "示例 / Example: total = name * qty",
    params: { context: "Left operand of \"*\"", actual: "string" },
  },
] as const satisfies readonly DiagnosticKeySpec<string>[];

export type AnalysisDiagnosticKey = (typeof ANALYSIS_DIAGNOSTIC_SPECS)[number]["key"];

export const RUNTIME_DIAGNOSTIC_SPECS = [
  {
    key: "builtin_if_arity",
    zh: "运行期 `if` 调用参数个数不正确。",
    en: "The runtime form of `if` was called with the wrong number of arguments.",
    example: "示例 / Example: evaluateBuiltinFunction(\"if\", [a, b])",
  },
  {
    key: "builtin_coalesce_arity",
    zh: "运行期 `coalesce` 至少需要一个参数。",
    en: "The runtime form of `coalesce` was called with zero arguments.",
    example: "示例 / Example: evaluateBuiltinFunction(\"coalesce\", [])",
  },
  {
    key: "builtin_and_arity",
    zh: "运行期 `and` 至少需要一个参数。",
    en: "The runtime form of `and` was called with zero arguments.",
    example: "示例 / Example: evaluateBuiltinFunction(\"and\", [])",
  },
  {
    key: "builtin_or_arity",
    zh: "运行期 `or` 至少需要一个参数。",
    en: "The runtime form of `or` was called with zero arguments.",
    example: "示例 / Example: evaluateBuiltinFunction(\"or\", [])",
  },
  {
    key: "boolean_compatible_required",
    zh: "运行期布尔位置拿到了非 boolean 值。",
    en: "A runtime boolean-only position received a non-boolean value.",
    example: "示例 / Example: if(numberValue, a, b)",
    params: { context: "Argument 1 of if", actual: "number" },
  },
  {
    key: "plot_axes_required",
    zh: "运行期 bar 图缺少 `x` 或 `y` 轴。",
    en: "A runtime bar plot was missing required axes.",
    example: "示例 / Example: compile plot without y",
    params: { table: "sales" },
  },
  {
    key: "number_runtime_required",
    zh: "运行期数值运算拿到了非 number 值。",
    en: "A runtime operation expected a number value but evaluated a different scalar type.",
    example: "示例 / Example: \"North\" * 2",
    params: { context: "Left operand of \"*\"", actual: "string" },
  },
  {
    key: "division_by_zero",
    zh: "发生了除零运算。",
    en: "A division operation attempted to divide by zero.",
    example: "示例 / Example: price / 0",
  },
  {
    key: "runtime_unknown_reference",
    zh: "运行期找不到列或局部变量引用。",
    en: "Runtime evaluation looked up a column/local reference that was not present.",
    example: "示例 / Example: reading missing local from executor context",
    params: { label: "local", name: "missing" },
  },
  {
    key: "plugin_scalar_return_required",
    zh: "plugin 返回了非标量值。",
    en: "A plugin returned a non-scalar value.",
    example: "示例 / Example: plugin returns object instead of number/string/boolean/null",
    params: { functionName: "finance.tax" },
  },
  {
    key: "compute_before_table",
    zh: "在表尚未 materialize 时执行了 `@compute`。",
    en: "A compute block was executed before its table had been materialized.",
    example: "示例 / Example: @compute sales appears before @table sales",
    params: { table: "sales" },
  },
  {
    key: "plot_before_table",
    zh: "在表尚未 materialize 时执行了 `@plot`。",
    en: "A plot block was executed before its table had been materialized.",
    example: "示例 / Example: @plot sales appears before @table sales",
    params: { table: "sales" },
  },
  {
    key: "plot_dependency_not_materialized",
    zh: "plot 依赖的列在运行期尚未 materialize。",
    en: "A plot depended on columns that had not yet been materialized at runtime.",
    example: "示例 / Example: plot consumes compute output before compute executes",
    params: { table: "sales", names: "total,taxed_total" },
  },
  {
    key: "runtime_missing_plot_dependency",
    zh: "plot 行投影时缺少某个依赖值。",
    en: "Plot row projection could not find a required dependency value.",
    example: "示例 / Example: row missing total during plot projection",
    params: { name: "total" },
  },
  {
    key: "runtime_missing_table_value",
    zh: "运行时表格缺少某列的单元格值。",
    en: "Table materialization encountered a missing runtime cell for a known column.",
    example: "示例 / Example: runtime row misses column total",
    params: { column: "total", table: "sales" },
  },
  {
    key: "compute_table_mismatch",
    zh: "compute 执行器收到的表与 compute 目标表不一致。",
    en: "A compute executor was asked to apply a compute block to the wrong table.",
    example: "示例 / Example: execute @compute sales against table inventory",
    params: { expected: "sales", actual: "inventory" },
  },
  {
    key: "missing_output_statement",
    zh: "声明为输出的 compute target 没有对应语句。",
    en: "An expected output target statement was missing from a compute block.",
    example: "示例 / Example: target: total[number] but no total = ...",
    params: { name: "total" },
  },
  {
    key: "plot_field_unknown",
    zh: "编译 plot 时引用了未知字段。",
    en: "A compiled plot referenced a field that was not in its resolved dependencies.",
    example: "示例 / Example: y references missing resolved field",
    params: { field: "y", table: "sales" },
  },
  {
    key: "plugin_export_not_function",
    zh: "plugin 指定的导出项不是函数。",
    en: "A selected plugin export was not a function.",
    example: "示例 / Example: export const tax = 1",
    params: { exportName: "tax", modulePath: "./plugins/finance.ts" },
  },
  {
    key: "plugin_module_extension_unsupported",
    zh: "plugin 模块使用了不支持的文件扩展名。",
    en: "A plugin module used an unsupported file extension.",
    example: "示例 / Example: path: ./plugins/finance.py",
    params: { extension: ".py" },
  },
  {
    key: "plugin_import_path_must_be_local",
    zh: "plugin 导入路径必须是本地路径。",
    en: "A plugin import path was not local.",
    example: "示例 / Example: import \"https://example.com/plugin.ts\"",
    params: { request: "https://example.com/plugin.ts" },
  },
  {
    key: "plugin_default_export_unsupported",
    zh: "plugin 模块使用了不支持的默认导出。",
    en: "A plugin module attempted to use a default export, which is unsupported.",
    example: "示例 / Example: export default function tax() {}",
  },
  {
    key: "relative_plugin_path_requires_file",
    zh: "在没有 sheet 文件路径上下文时使用了相对 plugin 路径。",
    en: "A relative plugin path was used without a base sheet file path.",
    example: "示例 / Example: readFromString(source) + path: ./plugins/finance.ts",
    params: { modulePath: "./plugins/finance.ts" },
  },
] as const satisfies readonly DiagnosticKeySpec<string>[];

export type RuntimeDiagnosticKey = (typeof RUNTIME_DIAGNOSTIC_SPECS)[number]["key"];
